/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedMinutesIndexRouteImport } from './routes/_authenticated/minutes.index'
import { Route as AuthenticatedMailIndexRouteImport } from './routes/_authenticated/mail.index'
import { Route as AuthenticatedCompanyIndexRouteImport } from './routes/_authenticated/company.index'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated/tasks.new'
import { Route as AuthenticatedTasksIdRouteImport } from './routes/_authenticated/tasks.$id'
import { Route as AuthenticatedReportsNewRouteImport } from './routes/_authenticated/reports.new'
import { Route as AuthenticatedReportsEquipeRouteImport } from './routes/_authenticated/reports.equipe'
import { Route as AuthenticatedReportsDirectionRouteImport } from './routes/_authenticated/reports.direction'
import { Route as AuthenticatedReportsAuditRolesRouteImport } from './routes/_authenticated/reports.audit-roles'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports.$id'
import { Route as AuthenticatedMinutesDashboardRouteImport } from './routes/_authenticated/minutes.dashboard'
import { Route as AuthenticatedMinutesIdRouteImport } from './routes/_authenticated/minutes.$id'
import { Route as AuthenticatedMailSettingsRouteImport } from './routes/_authenticated/mail.settings'
import { Route as AuthenticatedMailScheduledRouteImport } from './routes/_authenticated/mail.scheduled'
import { Route as AuthenticatedMailInboxRouteImport } from './routes/_authenticated/mail.inbox'
import { Route as AuthenticatedCompanyHierarchieRouteImport } from './routes/_authenticated/company.hierarchie'
import { Route as AuthenticatedCompanyApplicationsRouteImport } from './routes/_authenticated/company.applications'
import { Route as AuthenticatedReportsIdIndexRouteImport } from './routes/_authenticated/reports.$id.index'
import { Route as ApiPublicMailDispatchScheduledRouteImport } from './routes/api/public/mail/dispatch-scheduled'
import { Route as ApiPublicAiTranscribeRouteImport } from './routes/api/public/ai/transcribe'
import { Route as ApiPublicAiSpeakRouteImport } from './routes/api/public/ai/speak'
import { Route as AuthenticatedReportsIdEditRouteImport } from './routes/_authenticated/reports.$id.edit'
import { Route as AuthenticatedCompanyEmployeesIdRouteImport } from './routes/_authenticated/company.employees.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinutesIndexRoute =
  AuthenticatedMinutesIndexRouteImport.update({
    id: '/minutes/',
    path: '/minutes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMailIndexRoute = AuthenticatedMailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyIndexRoute =
  AuthenticatedCompanyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIdRoute = AuthenticatedTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsNewRoute = AuthenticatedReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsEquipeRoute =
  AuthenticatedReportsEquipeRouteImport.update({
    id: '/reports/equipe',
    path: '/reports/equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsDirectionRoute =
  AuthenticatedReportsDirectionRouteImport.update({
    id: '/reports/direction',
    path: '/reports/direction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAuditRolesRoute =
  AuthenticatedReportsAuditRolesRouteImport.update({
    id: '/reports/audit-roles',
    path: '/reports/audit-roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinutesDashboardRoute =
  AuthenticatedMinutesDashboardRouteImport.update({
    id: '/minutes/dashboard',
    path: '/minutes/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinutesIdRoute = AuthenticatedMinutesIdRouteImport.update({
  id: '/minutes/$id',
  path: '/minutes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMailSettingsRoute =
  AuthenticatedMailSettingsRouteImport.update({
    id: '/mail/settings',
    path: '/mail/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMailScheduledRoute =
  AuthenticatedMailScheduledRouteImport.update({
    id: '/mail/scheduled',
    path: '/mail/scheduled',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMailInboxRoute = AuthenticatedMailInboxRouteImport.update({
  id: '/mail/inbox',
  path: '/mail/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyHierarchieRoute =
  AuthenticatedCompanyHierarchieRouteImport.update({
    id: '/hierarchie',
    path: '/hierarchie',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyApplicationsRoute =
  AuthenticatedCompanyApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedReportsIdIndexRoute =
  AuthenticatedReportsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsIdRoute,
  } as any)
const ApiPublicMailDispatchScheduledRoute =
  ApiPublicMailDispatchScheduledRouteImport.update({
    id: '/api/public/mail/dispatch-scheduled',
    path: '/api/public/mail/dispatch-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiTranscribeRoute = ApiPublicAiTranscribeRouteImport.update({
  id: '/api/public/ai/transcribe',
  path: '/api/public/ai/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiSpeakRoute = ApiPublicAiSpeakRouteImport.update({
  id: '/api/public/ai/speak',
  path: '/api/public/ai/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsIdEditRoute =
  AuthenticatedReportsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedReportsIdRoute,
  } as any)
const AuthenticatedCompanyEmployeesIdRoute =
  AuthenticatedCompanyEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/company': typeof AuthenticatedCompanyRouteWithChildren
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/share/$token': typeof ShareTokenRoute
  '/company/applications': typeof AuthenticatedCompanyApplicationsRoute
  '/company/hierarchie': typeof AuthenticatedCompanyHierarchieRoute
  '/mail/inbox': typeof AuthenticatedMailInboxRoute
  '/mail/scheduled': typeof AuthenticatedMailScheduledRoute
  '/mail/settings': typeof AuthenticatedMailSettingsRoute
  '/minutes/$id': typeof AuthenticatedMinutesIdRoute
  '/minutes/dashboard': typeof AuthenticatedMinutesDashboardRoute
  '/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/reports/audit-roles': typeof AuthenticatedReportsAuditRolesRoute
  '/reports/direction': typeof AuthenticatedReportsDirectionRoute
  '/reports/equipe': typeof AuthenticatedReportsEquipeRoute
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/company/': typeof AuthenticatedCompanyIndexRoute
  '/mail/': typeof AuthenticatedMailIndexRoute
  '/minutes/': typeof AuthenticatedMinutesIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/company/employees/$id': typeof AuthenticatedCompanyEmployeesIdRoute
  '/reports/$id/edit': typeof AuthenticatedReportsIdEditRoute
  '/api/public/ai/speak': typeof ApiPublicAiSpeakRoute
  '/api/public/ai/transcribe': typeof ApiPublicAiTranscribeRoute
  '/api/public/mail/dispatch-scheduled': typeof ApiPublicMailDispatchScheduledRoute
  '/reports/$id/': typeof AuthenticatedReportsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/share/$token': typeof ShareTokenRoute
  '/company/applications': typeof AuthenticatedCompanyApplicationsRoute
  '/company/hierarchie': typeof AuthenticatedCompanyHierarchieRoute
  '/mail/inbox': typeof AuthenticatedMailInboxRoute
  '/mail/scheduled': typeof AuthenticatedMailScheduledRoute
  '/mail/settings': typeof AuthenticatedMailSettingsRoute
  '/minutes/$id': typeof AuthenticatedMinutesIdRoute
  '/minutes/dashboard': typeof AuthenticatedMinutesDashboardRoute
  '/reports/audit-roles': typeof AuthenticatedReportsAuditRolesRoute
  '/reports/direction': typeof AuthenticatedReportsDirectionRoute
  '/reports/equipe': typeof AuthenticatedReportsEquipeRoute
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/company': typeof AuthenticatedCompanyIndexRoute
  '/mail': typeof AuthenticatedMailIndexRoute
  '/minutes': typeof AuthenticatedMinutesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/company/employees/$id': typeof AuthenticatedCompanyEmployeesIdRoute
  '/reports/$id/edit': typeof AuthenticatedReportsIdEditRoute
  '/api/public/ai/speak': typeof ApiPublicAiSpeakRoute
  '/api/public/ai/transcribe': typeof ApiPublicAiTranscribeRoute
  '/api/public/mail/dispatch-scheduled': typeof ApiPublicMailDispatchScheduledRoute
  '/reports/$id': typeof AuthenticatedReportsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/company': typeof AuthenticatedCompanyRouteWithChildren
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/company/applications': typeof AuthenticatedCompanyApplicationsRoute
  '/_authenticated/company/hierarchie': typeof AuthenticatedCompanyHierarchieRoute
  '/_authenticated/mail/inbox': typeof AuthenticatedMailInboxRoute
  '/_authenticated/mail/scheduled': typeof AuthenticatedMailScheduledRoute
  '/_authenticated/mail/settings': typeof AuthenticatedMailSettingsRoute
  '/_authenticated/minutes/$id': typeof AuthenticatedMinutesIdRoute
  '/_authenticated/minutes/dashboard': typeof AuthenticatedMinutesDashboardRoute
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/_authenticated/reports/audit-roles': typeof AuthenticatedReportsAuditRolesRoute
  '/_authenticated/reports/direction': typeof AuthenticatedReportsDirectionRoute
  '/_authenticated/reports/equipe': typeof AuthenticatedReportsEquipeRoute
  '/_authenticated/reports/new': typeof AuthenticatedReportsNewRoute
  '/_authenticated/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
  '/_authenticated/company/': typeof AuthenticatedCompanyIndexRoute
  '/_authenticated/mail/': typeof AuthenticatedMailIndexRoute
  '/_authenticated/minutes/': typeof AuthenticatedMinutesIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/company/employees/$id': typeof AuthenticatedCompanyEmployeesIdRoute
  '/_authenticated/reports/$id/edit': typeof AuthenticatedReportsIdEditRoute
  '/api/public/ai/speak': typeof ApiPublicAiSpeakRoute
  '/api/public/ai/transcribe': typeof ApiPublicAiTranscribeRoute
  '/api/public/mail/dispatch-scheduled': typeof ApiPublicMailDispatchScheduledRoute
  '/_authenticated/reports/$id/': typeof AuthenticatedReportsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/admin'
    | '/apps'
    | '/company'
    | '/plans'
    | '/profile'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/share/$token'
    | '/company/applications'
    | '/company/hierarchie'
    | '/mail/inbox'
    | '/mail/scheduled'
    | '/mail/settings'
    | '/minutes/$id'
    | '/minutes/dashboard'
    | '/reports/$id'
    | '/reports/audit-roles'
    | '/reports/direction'
    | '/reports/equipe'
    | '/reports/new'
    | '/tasks/$id'
    | '/tasks/new'
    | '/company/'
    | '/mail/'
    | '/minutes/'
    | '/reports/'
    | '/tasks/'
    | '/company/employees/$id'
    | '/reports/$id/edit'
    | '/api/public/ai/speak'
    | '/api/public/ai/transcribe'
    | '/api/public/mail/dispatch-scheduled'
    | '/reports/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/admin'
    | '/apps'
    | '/plans'
    | '/profile'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/share/$token'
    | '/company/applications'
    | '/company/hierarchie'
    | '/mail/inbox'
    | '/mail/scheduled'
    | '/mail/settings'
    | '/minutes/$id'
    | '/minutes/dashboard'
    | '/reports/audit-roles'
    | '/reports/direction'
    | '/reports/equipe'
    | '/reports/new'
    | '/tasks/$id'
    | '/tasks/new'
    | '/company'
    | '/mail'
    | '/minutes'
    | '/reports'
    | '/tasks'
    | '/company/employees/$id'
    | '/reports/$id/edit'
    | '/api/public/ai/speak'
    | '/api/public/ai/transcribe'
    | '/api/public/mail/dispatch-scheduled'
    | '/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/apps'
    | '/_authenticated/company'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/share/$token'
    | '/_authenticated/company/applications'
    | '/_authenticated/company/hierarchie'
    | '/_authenticated/mail/inbox'
    | '/_authenticated/mail/scheduled'
    | '/_authenticated/mail/settings'
    | '/_authenticated/minutes/$id'
    | '/_authenticated/minutes/dashboard'
    | '/_authenticated/reports/$id'
    | '/_authenticated/reports/audit-roles'
    | '/_authenticated/reports/direction'
    | '/_authenticated/reports/equipe'
    | '/_authenticated/reports/new'
    | '/_authenticated/tasks/$id'
    | '/_authenticated/tasks/new'
    | '/_authenticated/company/'
    | '/_authenticated/mail/'
    | '/_authenticated/minutes/'
    | '/_authenticated/reports/'
    | '/_authenticated/tasks/'
    | '/_authenticated/company/employees/$id'
    | '/_authenticated/reports/$id/edit'
    | '/api/public/ai/speak'
    | '/api/public/ai/transcribe'
    | '/api/public/mail/dispatch-scheduled'
    | '/_authenticated/reports/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiPublicAiSpeakRoute: typeof ApiPublicAiSpeakRoute
  ApiPublicAiTranscribeRoute: typeof ApiPublicAiTranscribeRoute
  ApiPublicMailDispatchScheduledRoute: typeof ApiPublicMailDispatchScheduledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minutes/': {
      id: '/_authenticated/minutes/'
      path: '/minutes'
      fullPath: '/minutes/'
      preLoaderRoute: typeof AuthenticatedMinutesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail/': {
      id: '/_authenticated/mail/'
      path: '/mail'
      fullPath: '/mail/'
      preLoaderRoute: typeof AuthenticatedMailIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company/': {
      id: '/_authenticated/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof AuthenticatedCompanyIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$id': {
      id: '/_authenticated/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthenticatedTasksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/new': {
      id: '/_authenticated/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AuthenticatedReportsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/equipe': {
      id: '/_authenticated/reports/equipe'
      path: '/reports/equipe'
      fullPath: '/reports/equipe'
      preLoaderRoute: typeof AuthenticatedReportsEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/direction': {
      id: '/_authenticated/reports/direction'
      path: '/reports/direction'
      fullPath: '/reports/direction'
      preLoaderRoute: typeof AuthenticatedReportsDirectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/audit-roles': {
      id: '/_authenticated/reports/audit-roles'
      path: '/reports/audit-roles'
      fullPath: '/reports/audit-roles'
      preLoaderRoute: typeof AuthenticatedReportsAuditRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minutes/dashboard': {
      id: '/_authenticated/minutes/dashboard'
      path: '/minutes/dashboard'
      fullPath: '/minutes/dashboard'
      preLoaderRoute: typeof AuthenticatedMinutesDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minutes/$id': {
      id: '/_authenticated/minutes/$id'
      path: '/minutes/$id'
      fullPath: '/minutes/$id'
      preLoaderRoute: typeof AuthenticatedMinutesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail/settings': {
      id: '/_authenticated/mail/settings'
      path: '/mail/settings'
      fullPath: '/mail/settings'
      preLoaderRoute: typeof AuthenticatedMailSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail/scheduled': {
      id: '/_authenticated/mail/scheduled'
      path: '/mail/scheduled'
      fullPath: '/mail/scheduled'
      preLoaderRoute: typeof AuthenticatedMailScheduledRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail/inbox': {
      id: '/_authenticated/mail/inbox'
      path: '/mail/inbox'
      fullPath: '/mail/inbox'
      preLoaderRoute: typeof AuthenticatedMailInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company/hierarchie': {
      id: '/_authenticated/company/hierarchie'
      path: '/hierarchie'
      fullPath: '/company/hierarchie'
      preLoaderRoute: typeof AuthenticatedCompanyHierarchieRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/applications': {
      id: '/_authenticated/company/applications'
      path: '/applications'
      fullPath: '/company/applications'
      preLoaderRoute: typeof AuthenticatedCompanyApplicationsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/reports/$id/': {
      id: '/_authenticated/reports/$id/'
      path: '/'
      fullPath: '/reports/$id/'
      preLoaderRoute: typeof AuthenticatedReportsIdIndexRouteImport
      parentRoute: typeof AuthenticatedReportsIdRoute
    }
    '/api/public/mail/dispatch-scheduled': {
      id: '/api/public/mail/dispatch-scheduled'
      path: '/api/public/mail/dispatch-scheduled'
      fullPath: '/api/public/mail/dispatch-scheduled'
      preLoaderRoute: typeof ApiPublicMailDispatchScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/transcribe': {
      id: '/api/public/ai/transcribe'
      path: '/api/public/ai/transcribe'
      fullPath: '/api/public/ai/transcribe'
      preLoaderRoute: typeof ApiPublicAiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/speak': {
      id: '/api/public/ai/speak'
      path: '/api/public/ai/speak'
      fullPath: '/api/public/ai/speak'
      preLoaderRoute: typeof ApiPublicAiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/$id/edit': {
      id: '/_authenticated/reports/$id/edit'
      path: '/edit'
      fullPath: '/reports/$id/edit'
      preLoaderRoute: typeof AuthenticatedReportsIdEditRouteImport
      parentRoute: typeof AuthenticatedReportsIdRoute
    }
    '/_authenticated/company/employees/$id': {
      id: '/_authenticated/company/employees/$id'
      path: '/employees/$id'
      fullPath: '/company/employees/$id'
      preLoaderRoute: typeof AuthenticatedCompanyEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
  }
}

interface AuthenticatedCompanyRouteChildren {
  AuthenticatedCompanyApplicationsRoute: typeof AuthenticatedCompanyApplicationsRoute
  AuthenticatedCompanyHierarchieRoute: typeof AuthenticatedCompanyHierarchieRoute
  AuthenticatedCompanyIndexRoute: typeof AuthenticatedCompanyIndexRoute
  AuthenticatedCompanyEmployeesIdRoute: typeof AuthenticatedCompanyEmployeesIdRoute
}

const AuthenticatedCompanyRouteChildren: AuthenticatedCompanyRouteChildren = {
  AuthenticatedCompanyApplicationsRoute: AuthenticatedCompanyApplicationsRoute,
  AuthenticatedCompanyHierarchieRoute: AuthenticatedCompanyHierarchieRoute,
  AuthenticatedCompanyIndexRoute: AuthenticatedCompanyIndexRoute,
  AuthenticatedCompanyEmployeesIdRoute: AuthenticatedCompanyEmployeesIdRoute,
}

const AuthenticatedCompanyRouteWithChildren =
  AuthenticatedCompanyRoute._addFileChildren(AuthenticatedCompanyRouteChildren)

interface AuthenticatedReportsIdRouteChildren {
  AuthenticatedReportsIdEditRoute: typeof AuthenticatedReportsIdEditRoute
  AuthenticatedReportsIdIndexRoute: typeof AuthenticatedReportsIdIndexRoute
}

const AuthenticatedReportsIdRouteChildren: AuthenticatedReportsIdRouteChildren =
  {
    AuthenticatedReportsIdEditRoute: AuthenticatedReportsIdEditRoute,
    AuthenticatedReportsIdIndexRoute: AuthenticatedReportsIdIndexRoute,
  }

const AuthenticatedReportsIdRouteWithChildren =
  AuthenticatedReportsIdRoute._addFileChildren(
    AuthenticatedReportsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRouteWithChildren
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMailInboxRoute: typeof AuthenticatedMailInboxRoute
  AuthenticatedMailScheduledRoute: typeof AuthenticatedMailScheduledRoute
  AuthenticatedMailSettingsRoute: typeof AuthenticatedMailSettingsRoute
  AuthenticatedMinutesIdRoute: typeof AuthenticatedMinutesIdRoute
  AuthenticatedMinutesDashboardRoute: typeof AuthenticatedMinutesDashboardRoute
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRouteWithChildren
  AuthenticatedReportsAuditRolesRoute: typeof AuthenticatedReportsAuditRolesRoute
  AuthenticatedReportsDirectionRoute: typeof AuthenticatedReportsDirectionRoute
  AuthenticatedReportsEquipeRoute: typeof AuthenticatedReportsEquipeRoute
  AuthenticatedReportsNewRoute: typeof AuthenticatedReportsNewRoute
  AuthenticatedTasksIdRoute: typeof AuthenticatedTasksIdRoute
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
  AuthenticatedMailIndexRoute: typeof AuthenticatedMailIndexRoute
  AuthenticatedMinutesIndexRoute: typeof AuthenticatedMinutesIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRouteWithChildren,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMailInboxRoute: AuthenticatedMailInboxRoute,
  AuthenticatedMailScheduledRoute: AuthenticatedMailScheduledRoute,
  AuthenticatedMailSettingsRoute: AuthenticatedMailSettingsRoute,
  AuthenticatedMinutesIdRoute: AuthenticatedMinutesIdRoute,
  AuthenticatedMinutesDashboardRoute: AuthenticatedMinutesDashboardRoute,
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRouteWithChildren,
  AuthenticatedReportsAuditRolesRoute: AuthenticatedReportsAuditRolesRoute,
  AuthenticatedReportsDirectionRoute: AuthenticatedReportsDirectionRoute,
  AuthenticatedReportsEquipeRoute: AuthenticatedReportsEquipeRoute,
  AuthenticatedReportsNewRoute: AuthenticatedReportsNewRoute,
  AuthenticatedTasksIdRoute: AuthenticatedTasksIdRoute,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
  AuthenticatedMailIndexRoute: AuthenticatedMailIndexRoute,
  AuthenticatedMinutesIndexRoute: AuthenticatedMinutesIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiPublicAiSpeakRoute: ApiPublicAiSpeakRoute,
  ApiPublicAiTranscribeRoute: ApiPublicAiTranscribeRoute,
  ApiPublicMailDispatchScheduledRoute: ApiPublicMailDispatchScheduledRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
