/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedReportsNewRouteImport } from './routes/_authenticated/reports.new'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports.$id'
import { Route as AuthenticatedReportsIdIndexRouteImport } from './routes/_authenticated/reports.$id.index'
import { Route as ApiPublicAiTranscribeRouteImport } from './routes/api/public/ai/transcribe'
import { Route as AuthenticatedReportsIdEditRouteImport } from './routes/_authenticated/reports.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsNewRoute = AuthenticatedReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIdIndexRoute =
  AuthenticatedReportsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsIdRoute,
  } as any)
const ApiPublicAiTranscribeRoute = ApiPublicAiTranscribeRouteImport.update({
  id: '/api/public/ai/transcribe',
  path: '/api/public/ai/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsIdEditRoute =
  AuthenticatedReportsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedReportsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/reports/$id/edit': typeof AuthenticatedReportsIdEditRoute
  '/api/public/ai/transcribe': typeof ApiPublicAiTranscribeRoute
  '/reports/$id/': typeof AuthenticatedReportsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/reports/$id/edit': typeof AuthenticatedReportsIdEditRoute
  '/api/public/ai/transcribe': typeof ApiPublicAiTranscribeRoute
  '/reports/$id': typeof AuthenticatedReportsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRouteWithChildren
  '/_authenticated/reports/new': typeof AuthenticatedReportsNewRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/reports/$id/edit': typeof AuthenticatedReportsIdEditRoute
  '/api/public/ai/transcribe': typeof ApiPublicAiTranscribeRoute
  '/_authenticated/reports/$id/': typeof AuthenticatedReportsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/profile'
    | '/reports/$id'
    | '/reports/new'
    | '/reports/'
    | '/reports/$id/edit'
    | '/api/public/ai/transcribe'
    | '/reports/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/profile'
    | '/reports/new'
    | '/reports'
    | '/reports/$id/edit'
    | '/api/public/ai/transcribe'
    | '/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/profile'
    | '/_authenticated/reports/$id'
    | '/_authenticated/reports/new'
    | '/_authenticated/reports/'
    | '/_authenticated/reports/$id/edit'
    | '/api/public/ai/transcribe'
    | '/_authenticated/reports/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAiTranscribeRoute: typeof ApiPublicAiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/new': {
      id: '/_authenticated/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AuthenticatedReportsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id/': {
      id: '/_authenticated/reports/$id/'
      path: '/'
      fullPath: '/reports/$id/'
      preLoaderRoute: typeof AuthenticatedReportsIdIndexRouteImport
      parentRoute: typeof AuthenticatedReportsIdRoute
    }
    '/api/public/ai/transcribe': {
      id: '/api/public/ai/transcribe'
      path: '/api/public/ai/transcribe'
      fullPath: '/api/public/ai/transcribe'
      preLoaderRoute: typeof ApiPublicAiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/$id/edit': {
      id: '/_authenticated/reports/$id/edit'
      path: '/edit'
      fullPath: '/reports/$id/edit'
      preLoaderRoute: typeof AuthenticatedReportsIdEditRouteImport
      parentRoute: typeof AuthenticatedReportsIdRoute
    }
  }
}

interface AuthenticatedReportsIdRouteChildren {
  AuthenticatedReportsIdEditRoute: typeof AuthenticatedReportsIdEditRoute
  AuthenticatedReportsIdIndexRoute: typeof AuthenticatedReportsIdIndexRoute
}

const AuthenticatedReportsIdRouteChildren: AuthenticatedReportsIdRouteChildren =
  {
    AuthenticatedReportsIdEditRoute: AuthenticatedReportsIdEditRoute,
    AuthenticatedReportsIdIndexRoute: AuthenticatedReportsIdIndexRoute,
  }

const AuthenticatedReportsIdRouteWithChildren =
  AuthenticatedReportsIdRoute._addFileChildren(
    AuthenticatedReportsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRouteWithChildren
  AuthenticatedReportsNewRoute: typeof AuthenticatedReportsNewRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRouteWithChildren,
  AuthenticatedReportsNewRoute: AuthenticatedReportsNewRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAiTranscribeRoute: ApiPublicAiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
